# Control file for continuous integration testing at http://travis-ci.org/
# taken from samtools
language: c
compiler:
  - clang
  - gcc

matrix:
  include:
    # An unoptimised C99 build, for detecting non-static inline functions
    - compiler: gcc
      env: CFLAGS="-std=gnu99 -O0"
addons:
  apt:
    packages:
    - liblzma-dev
    - libbz2-dev

before_script:
  - git clone --branch=develop git://github.com/samtools/htslib.git
  - cd htslib;git checkout ee0f7f356cbdde7a00a8fc4d24ab0; make;cd ..
  - git clone --depth=5 git://github.com/ANGSD/smallBam.git
  - export HTSSRC=`pwd`/htslib
script: make -e
